node:events:492
      throw er; // Unhandled 'error' event
      ^

MongoNetworkError: connection 6 to 159.41.168.15:27017 closed
    at Connection.onClose (G:\Project\AgroConnect\server\node_modules\mongodb\lib\cmap\connection.js:121:28)
    at TLSSocket.<anonymous> (G:\Project\AgroConnect\server\node_modules\mongodb\lib\cmap\connection.js:63:46)
    at TLSSocket.emit (node:events:514:28)
    at node:net:337:12
    at TCP.done (node:_tls_wrap:657:7)
Emitted 'error' event on ChangeStream instance at:
    at ChangeStream.<anonymous> (G:\Project\AgroConnect\server\node_modules\mongoose\lib\cursor\ChangeStream.js:83:14)
    at ChangeStream.emit (node:events:514:28)
    at ChangeStream._closeEmitterModeWithError (G:\Project\AgroConnect\server\node_modules\mongodb\lib\change_stream.js:276:14)
    at Object.callback (G:\Project\AgroConnect\server\node_modules\mongodb\lib\change_stream.js:336:33)
    at Timeout._onTimeout (G:\Project\AgroConnect\server\node_modules\mongodb\lib\sdam\topology.js:279:33)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  [Symbol(errorLabels)]: Set(2) { 'RetryableWriteError', 'ResetPool' }
}

Node.js v20.9.0
